### ISSUE TITLE
libFuzzer trunk doesn't build with clang-3.8 anymore

### ISSUE THREAD

**Issue by attekett** [ouspg/libfuzzerfication#104]
$ docker-compose build libfuzzer-base
.
.
.
Step 6 : RUN mkdir /src /work &&     cd /src &&     git clone https://chromium.googlesource.com/chromium/llvm-project/llvm/lib/Fuzzer &&     clang++ -c -g -O2 -std=c++11 Fuzzer/*.cpp -IFuzzer &&     ar ruv libFuzzer.a Fuzzer*.o &&     mkdir -p /work/libfuzzer &&     mv libFuzzer.a /usr/local/lib &&     rm *.o &&     rm -rf Fuzzer
 ---> Running in ba768abc1e98
Cloning into 'Fuzzer'...
Fuzzer/FuzzerTracePC.cpp:193:3: error: use of undeclared identifier '__sanitizer_dump_coverage'
  __sanitizer_dump_coverage(PCs, GetNumPCs());
  ^
1 error generated.

We have to change clang to a newer version, or checkout libFuzzer @ 34a77f5afc4efc03323a70e4f68b092f36f8a89b
